### ISSUE TITLE
Error while crawling

### ISSUE THREAD

**Issue by Laterality** [Laterality/sibylla#6]
```
168 articles found
Done with 3 timeouts and 1 skipped pages in 168 links
33 articles found
Done with 0 timeouts and 0 skipped pages in 33 links
Traceback (most recent call last):
  File "src/main.py", line 7, in <module>
    crawler_donga.crawl()
  File "/usr/src/app/src/crawler_donga.py", line 56, in crawl
    driver.get(MAIN_URL)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 332, in get
    self.execute(Command.GET, {'url': url})
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 320, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout
  (Session info: headless chrome=69.0.3497.100)
  (Driver info: chromedriver=2.42.591071 (0b695ff80972cc1a65a5cd643186d2ae582cd4ac),platform=Linux 3.10.0-862.11.6.el7.x86_64 x86_64)
```

**Comment by Laterality** [comment]
Temporarily disabled the script.
